metadata-version = "2015-12-19"
log-level = "debug"
interval = 10
onetime = false

[[ template ]]
source = "/etc/rancher-conf/reload.sh.tmpl"
dest = "/etc/rancher-conf/reload.sh"
notify-cmd = "sh /etc/rancher-conf/reload.sh"
notify-output = true

[[ template ]]
source = "/etc/rancher-conf/prometheus.yml.tmpl"
dest = "/etc/rancher-conf/prometheus.yml"
notify-cmd = "sh /etc/rancher-conf/reload.sh"
notify-output = true
